[env]
LLVM_SYS_140_PREFIX = "/usr/lib/llvm-14"
LLVM_SYS_140_STRICT_VERSIONING = "false"

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-L/usr/lib/llvm-14/lib",
    "-C", "link-arg=-Wl,-rpath,/usr/lib/llvm-14/lib"
]
